// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.598
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import layout "github.com/andreiz53/web-scraper/views/layout"

func Home() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<h1 class=\"text-center\">SEO Web Scraper</h1><p class=\"text-center\">Enter your website and check your SEO vitals.</p><div class=\"flex justify-center my-8 \"><form class=\"flex max-w-xl w-full shadow\" hx-post=\"/website\" hx-target=\"#results\" hx-indicator=\"#loading\"><input type=\"text\" name=\"website\" id=\"website\" autocomplete=\"off\" placeholder=\"Enter your website&#39;s URL\" class=\"px-6 py-4 m-0 font-semibold rounded-l-8 w-full\"> <button type=\"submit\" class=\"cursor-pointer bg-blue-400 text-white b-0 m-0 px-8 font-semibold rounded-r-8\">Check</button></form></div><h4 class=\"htmx-indicator text-center\" id=\"loading\">Loading...</h4><div id=\"results\" class=\"max-w-3xl mx-auto\"></div><script>\r\n\t\t\t\t\twindow.addEventListener(\"DOMContentLoaded\", () => {\r\n\t\t\t\t\t\tdocument.getElementById(\"website\").focus()\r\n\t\t\t\t\t})\r\n\t\t\t\t</script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layout.Page("Homepage").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
